name: Binaries
on:
  push:
    branches:
      - main
jobs:
  ensure_release:
    runs-on: ubuntu-18.04
    steps:
      - uses: actions/checkout@v2
      - run: .github/scripts/ensure_release.sh
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
  linux:
    runs-on: ubuntu-latest
    needs: [ensure_release]
    steps:
      - uses: actions/checkout@v2
      - uses: erlef/setup-beam@v1
        with:
          otp-version: '23.3'
          elixir-version: '1.11'
      - run: mix deps.get
      - run: mix test
      - run: .github/scripts/upload_nif.sh
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

      - run: rm deps/cmark/priv/cmark.so 
      - run: CC=clang MIX_ENV=test OPTFLAGS="-target aarch64-linux-gnu" mix deps.compile --force
      - run: .github/scripts/upload_nif.sh
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
  macos:
    runs-on: macos-10.15
    needs: [ensure_release]
    steps:
      - uses: actions/checkout@v2
      - run: brew install elixir
      - run: mix local.hex --force
      - run: mix deps.get
      - run: mix test
      - run: .github/scripts/upload_nif.sh
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
  # windows:
  #   runs-on: windows-2019
  #   needs: [ensure_release]
  #   steps:
  #     - uses: actions/checkout@v2
  #     - uses: ilammy/msvc-dev-cmd@v1
  #     - uses: actions/cache@v2
  #       with:
  #         path: C:\Users\runneradmin\AppData\Local\Temp\chocolatey\erlang
  #         key: erlang-22.3-windows-2019
  #     - uses: actions/cache@v2
  #       with:
  #         path: C:\Users\runneradmin\AppData\Local\Temp\chocolatey\elixir
  #         key: elixir-1.11.2-windows-2019
  #     - name: Install Elixir
  #       run: choco install -y elixir --version 1.11.2
  #     - run: c:\ProgramData\chocolatey\lib\Elixir\bin\mix local.hex --force
  #       shell: cmd
  #     - run: c:\ProgramData\chocolatey\lib\Elixir\bin\mix deps.get
  #       shell: cmd
  #     - run: c:\ProgramData\chocolatey\lib\Elixir\bin\mix test
  #       shell: cmd
  #     - run: .github/scripts/upload_nif.sh
  #       env:
  #         GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
